_target_: fusion_bench.modelpool.CausalLMPool
models:
  _pretrained_: meta-llama/Llama-3.2-1B
  bengali: baban/MT_En_Bengali
  tamil: baban/MT_En_Tamil
  telugu: baban/MT_En_Telugu
model_kwargs:
  torch_dtype: bfloat16
tokenizer: meta-llama/Llama-3.2-1B
