_target_: fusion_bench.method.trust_region.tatr_llm.TaskArithmeticWithTrustRegionForCausalLM
scaling_factor: 0.3
threshold_quantile: 0.99
max_samples: 128
batch_size: 128
zero_shot: true
tokenizer: meta-llama/Llama-3.2-1B
